language: php

sudo: false

env:
  global:
    - COMPOSER_ROOT_VERSION=2.0.x-dev
    - CORE_RELEASE=master

matrix:
  include:
    - php: 5.6
      env:
        - PHPUNIT_TEST=1
        - DB=PGSQL
    - php: 5.6
      env:
        - PHPUNIT_TEST=1
        - DB=MYSQL
    - php: 5.6
      env:
        - PHPCS_TEST=1
        - DB=MYSQL

before_script:
 - if [[ $PHPCS_TEST ]]; then pyrus install pear/PHP_CodeSniffer; fi
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script:
 - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit testsession/tests/; fi
 - if [[ $PHPCS_TEST ]]; then (cd testsession && composer run-script lint); fi
