---
Name: requestprocessors
---
Injector:
  RequestProcessor:
    properties:
      filters:
        - '%$TestSessionRequestFilter'
Member:
  extensions:
    - TestSessionMemberExtension
---
Name: testsession-setup
---
TestSessionEnvironment:
  test_state_file: TESTS_RUNNING.json